version: "3.8"

services:
  app:
    container_name: python-telebot
    build: ./project
    volumes:
      - ./project:/project
    restart: unless-stopped

  restarter:
    container_name: bot-restarter
    image: docker:cli
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      [
        "/bin/sh",
        "-c",
        "while true; do sleep 86400; docker restart python-telebot; done",
      ]
    restart: unless-stopped
